### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by luluwaza** [IGLADI/IT-project-Ethereal-Hyperspace-Battleships#13]
/travel - used to travel to specific coordinates, this has a cooldown and a waiting time
/mine - make it possible to mine resources. This should also have a cooldown.

**Comment by IGLADI** [comment]
/help /register have been added
/help should be continuously been updated with new commands (and a intro message)
/register created a user account, this will probably be changed to let the user choose a display name instead of using the discord username as display name

**Comment by ThomasKnoops** [comment]
/ship (give description of your ship)
/upgrade (to upgrade a module of your ship)

--> Both have been added in the issue "basic ship"

**Comment by IGLADI** [comment]
/mine should be implemented in [Resources: Issue #14](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/issues/14)

**Comment by IGLADI** [comment]
The travel system should probably be done in another issue travel/location system.

**Comment by IGLADI** [comment]
Discussed in team, this become base commands, feature linked commands are made in their issue
