### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by luluwaza** [IGLADI/IT-project-Ethereal-Hyperspace-Battleships#15]
Global currency troughout the game. Will also be used in the casino.

**Comment by IGLADI** [comment]
Base money system implemented, needs to be moved to the db when created.
/pay /balance have been added 
(/get_betted_amount has also been added to work with the hello world app (casino racing game))

**Comment by IGLADI** [comment]
> Base money system implemented, needs to be moved to the db when created. /pay /balance have been added /pay sends money to another player /balance shows your current balance (-betted amount) (/get_betted_amount has also been added to work with the hello world app (casino racing game) and work with /balance)

Base money system has been jugged to be done (mooving the info to the db will be fixed in [Issue#27](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/issues/27))
